SELECT [FrontPagePostListaId]
      ,[do0FrontPagePostsId]
      ,[do0AvatarName]
      ,[do0UserName]
      ,[Rascunho]
      ,[Autor]
      ,[Data]
      ,[Titulo]
      ,[Introducao]
      ,[Descricao]
      ,[Pasta]
      ,[LinkExterno]
      ,[LinkUrl]
      ,[Reserva1]
  FROM [FrontPagePostListas];
GO
